// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Main$Main(props) {
  return React.createElement("div", undefined, "Hello World");
}

var Main = {
  make: Main$Main
};

export {
  Main ,
}
/* react Not a pure module */
