// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Timer from "./Timer.bs.js";
import * as React from "react";

function Main$Main(props) {
  var match = React.useState(function () {
        return false;
      });
  var setIsActive = match[1];
  var isActive = match[0];
  var startClock = function ($$event) {
    Curry._1(setIsActive, (function (param) {
            return !isActive;
          }));
  };
  return React.createElement("div", {
              className: "flex h-screen justify-center px-4 py-16 bg-base-200"
            }, React.createElement("div", {
                  className: "m-auto"
                }, React.createElement(Timer.Timer.make, {
                      isActive: isActive
                    }), React.createElement("button", {
                      className: "btn btn-primary",
                      onClick: startClock
                    }, "Start session")));
}

var Main = {
  make: Main$Main
};

export {
  Main ,
}
/* Timer Not a pure module */
