// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

import { UseBell } from "./UseBell.ts";
;

function Timer$Timer(props) {
  var isActive = props.isActive;
  var match = React.useState(function () {
        return 0;
      });
  var setMilliseconds = match[1];
  var milliseconds = match[0];
  React.useEffect(function () {
        var updateTime = function (param) {
          Curry._1(setMilliseconds, (function (param) {
                  return milliseconds + 1000 | 0;
                }));
        };
        if (!isActive) {
          return ;
        }
        var interval = setInterval(updateTime, 1000);
        return (function (param) {
                  clearInterval(interval);
                });
      });
  var play = milliseconds % 300000 === 0 && isActive ? (<UseBell />) : React.createElement(React.Fragment, undefined);
  var minutes = String(milliseconds / 60000 | 0);
  var seconds = String(milliseconds % 60000 / 1000 | 0);
  var time = minutes + ":" + seconds;
  return React.createElement(React.Fragment, undefined, React.createElement("div", {
                  className: "text-center"
                }, time), play);
}

var Timer = {
  make: Timer$Timer
};

export {
  Timer ,
}
/*  Not a pure module */
